name: digisina
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.1
  get_it: ^7.1.4
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  flutter_secure_storage: ^4.2.1
  time: 2.0.0
  curved_navigation_bar: ^1.0.1
  flutter_svg: ^0.22.0
  json_annotation: ^4.0.1
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  dots_indicator: ^2.0.0
  readmore: ^2.1.0
  fijkplayer: ^0.10.0
  shared_preferences: ^2.0.6
  visibility_detector: ^0.2.0
  jalali_calendar: ^1.0.4
  photo_view: ^0.12.0
  sliver_tools: ^0.2.5
  cool_alert: ^1.1.0
  dio: ^4.0.0
  webview_flutter: ^2.0.10
  oktoast:

  open_file: ^3.2.1
  pdf: ^3.4.2
  path_provider: ^2.0.2
  advance_pdf_viewer: ^2.0.0
  collection: ^1.15.0
  flutter_keyboard_visibility: ^5.0.3
  uni_links: ^0.5.1
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.6
  #printing:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^4.1.3
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: false
  ios: true
  image_path: "assets/playstore.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: fonts/YekanBakhFat.ttf
          weight: 900
        - asset: fonts/YekanBakhHeavy.ttf
          weight: 800
        - asset: fonts/YekanBakhBold.ttf
          weight: 700
        - asset: fonts/YekanBakhMedium.ttf
          weight: 500
        - asset: fonts/YekanBakhRegular.ttf
          weight: 400
        - asset: fonts/YekanBakhLight.ttf
          weight: 300
        - asset: fonts/YekanBakhThin.ttf
          weight: 200
        - asset: fonts/YekanBakhHairline.ttf
          weight: 100

    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
